-- MySQL Script generated by MySQL Workbench
-- Tue Dec 26 10:58:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema scmdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scmdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scmdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `scmdb` ;

-- -----------------------------------------------------
-- Table `scmdb`.`idc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scmdb`.`idc` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `name` VARCHAR(100) NOT NULL COMMENT 'idc名称',
  `address` VARCHAR(100) NULL COMMENT '地址',
  `status` VARCHAR(100) NULL DEFAULT '正常' COMMENT '状态(正常;异常)',
  `contact` VARCHAR(100) NULL COMMENT '联系人',
  `telephone` VARCHAR(100) NULL COMMENT '联系电话',
  `floor` VARCHAR(100) NULL COMMENT '楼层',
  `province` VARCHAR(100) NULL COMMENT '省',
  `city` VARCHAR(100) NULL COMMENT '市',
  `district` VARCHAR(100) NULL COMMENT '区',
  `operator` VARCHAR(100) NULL COMMENT '运营商',
  `stars` INT NULL DEFAULT 5 COMMENT '星级',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `scmdb`.`rack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scmdb`.`rack` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rackcode` VARCHAR(100) CHARACTER SET 'swe7' NOT NULL COMMENT '机柜号',
  `floor` VARCHAR(100) NULL COMMENT '楼层',
  `room` VARCHAR(100) NULL COMMENT '房间号',
  `idc_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rack_idc_idx` (`idc_id` ASC),
  CONSTRAINT `fk_rack_idc`
    FOREIGN KEY (`idc_id`)
    REFERENCES `scmdb`.`idc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `scmdb`.`server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scmdb`.`server` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `brand` VARCHAR(100) NULL COMMENT '品牌',
  `model_number` VARCHAR(100) NULL COMMENT '型号',
  `sn` VARCHAR(100) NULL COMMENT '序列化',
  `status` VARCHAR(100) NULL COMMENT '状态',
  `form_factor` VARCHAR(100) NULL COMMENT '规格',
  `multi_thread` VARCHAR(100) NULL COMMENT '多线程',
  `drivers_detail` VARCHAR(100) NULL COMMENT '磁盘详情',
  `console_ip` VARCHAR(100) NULL COMMENT '控制台IP',
  `control_type` VARCHAR(100) NULL COMMENT '类型[\'虚拟化\',\'物理机\']',
  `affliated_area` VARCHAR(100) NULL COMMENT '关联区域',
  `os` VARCHAR(100) NULL COMMENT '操作系统',
  `ipmi_user` VARCHAR(100) NULL COMMENT 'ipmi密码',
  `kvm_ip` VARCHAR(100) NULL,
  `kvm_pwd` VARCHAR(100) NULL COMMENT 'kvmip',
  `position` VARCHAR(100) NULL COMMENT '物理位置',
  `raid_cache_s` VARCHAR(100) NULL COMMENT '阵列缓存大小',
  `machine_area` VARCHAR(100) NULL COMMENT '域',
  `remark` VARCHAR(100) NULL COMMENT '备注',
  `processors` INT NULL COMMENT '处理器数',
  `cores` INT NULL COMMENT '核数',
  `logical_processor` INT NULL COMMENT '逻辑核数',
  `memory` INT(64) NULL COMMENT '内存',
  `storage` INT(64) NULL COMMENT '磁盘阵列大小',
  `rack_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_server_rack1_idx` (`rack_id` ASC),
  CONSTRAINT `fk_server_rack1`
    FOREIGN KEY (`rack_id`)
    REFERENCES `scmdb`.`rack` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `scmdb`.`vm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scmdb`.`vm` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL COMMENT '虚拟机名',
  `os` VARCHAR(100) NULL COMMENT '操作系统',
  `inner_ip` VARCHAR(100) NULL COMMENT '内网ip',
  `pwd` VARCHAR(100) NULL COMMENT '密码',
  `use` VARCHAR(100) NULL COMMENT '用途',
  `contact` VARCHAR(100) NULL COMMENT '联系人',
  `status` VARCHAR(100) NULL COMMENT '状态[\'启用\',\'停用\']',
  `remarks` VARCHAR(200) NULL COMMENT '备注',
  `wk_no` VARCHAR(100) NULL COMMENT '工单号',
  `server_type` VARCHAR(100) NULL COMMENT '服务器类型',
  `cores` INT NULL COMMENT '核数',
  `ram` INT(64) NULL COMMENT '内存（M）',
  `hdd` INT(64) NULL COMMENT '磁盘容量',
  `assigned_date` DATETIME NULL COMMENT '分配时间',
  `end_date` DATETIME NULL COMMENT '到期时间',
  `server_id` INT NOT NULL,
  `case_id` VARCHAR(100) NULL COMMENT '部署实例id',
  PRIMARY KEY (`id`),
  INDEX `fk_vm_server1_idx` (`server_id` ASC),
  CONSTRAINT `fk_vm_server1`
    FOREIGN KEY (`server_id`)
    REFERENCES `scmdb`.`server` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `scmdb`.`mysql`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scmdb`.`mysql` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vip` VARCHAR(100) NULL,
  `version` VARCHAR(100) NULL COMMENT '数据库版本',
  `comment` VARCHAR(100) NULL COMMENT '备注',
  `rootuser` VARCHAR(100) NULL COMMENT 'root用户（发现有root用户不叫root的情况）',
  `rootpwd` VARCHAR(100) NULL COMMENT 'root密码',
  `port` INT NULL COMMENT '端口号',
  `dbrole` INT NULL COMMENT '数据库角色[1:主机;2:备机;3:单机]',
  `vm_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mysql_vm1_idx` (`vm_id` ASC),
  CONSTRAINT `fk_mysql_vm1`
    FOREIGN KEY (`vm_id`)
    REFERENCES `scmdb`.`vm` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `scmdb`.`mysql_schema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scmdb`.`mysql_schema` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL COMMENT 'schema名字',
  `mysql_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mysql_schema_mysql1_idx` (`mysql_id` ASC),
  CONSTRAINT `fk_mysql_schema_mysql1`
    FOREIGN KEY (`mysql_id`)
    REFERENCES `scmdb`.`mysql` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `scmdb`.`mysql_schema_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scmdb`.`mysql_schema_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL COMMENT '账号名',
  `password` VARCHAR(100) NULL COMMENT '账号密码',
  `permission` INT NULL COMMENT '权限[1:只读,2:读写]',
  `type` INT NULL COMMENT '账号类型[1:业务,2:个人]',
  `mysql_schema_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mysql_schema_user_mysql_schema1_idx` (`mysql_schema_id` ASC),
  CONSTRAINT `fk_mysql_schema_user_mysql_schema1`
    FOREIGN KEY (`mysql_schema_id`)
    REFERENCES `scmdb`.`mysql_schema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `scmdb`.`innerip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scmdb`.`innerip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(100) NULL COMMENT '内网ip地址',
  `affliated_area` VARCHAR(100) NULL COMMENT '所属区域',
  `vlan` VARCHAR(100) NULL COMMENT 'vlan',
  `remarks` VARCHAR(200) NULL COMMENT '备注',
  `status` INT NULL COMMENT '状态[0.空闲;1.使用;2.DHCP;3.保留;4.上锁]',
  `idc_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_innerip_idc1_idx` (`idc_id` ASC),
  CONSTRAINT `fk_innerip_idc1`
    FOREIGN KEY (`idc_id`)
    REFERENCES `scmdb`.`idc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `scmdb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scmdb`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `rbac_id` INT NULL,
  `email` VARCHAR(100) NULL,
  `telephone` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `scmdb`.`pubip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scmdb`.`pubip` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '公网ip',
  `address` VARCHAR(100) NOT NULL,
  `carrier` VARCHAR(100) NULL COMMENT '运营商',
  `status` VARCHAR(100) NULL COMMENT '状态(0.未用;1.已用)',
  `comment` VARCHAR(200) NULL COMMENT '备注',
  `affliated_area` VARCHAR(100) NULL COMMENT '所属区域',
  `idc_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `address_UNIQUE` (`address` ASC),
  INDEX `fk_pubip_idc1_idx` (`idc_id` ASC),
  CONSTRAINT `fk_pubip_idc1`
    FOREIGN KEY (`idc_id`)
    REFERENCES `scmdb`.`idc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `scmdb`.`ipport_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scmdb`.`ipport_map` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ip:port映射',
  `pubip` VARCHAR(100) NOT NULL,
  `pubport_begin` VARCHAR(100) NOT NULL,
  `pubport_end` VARCHAR(100) NOT NULL,
  `innerip` VARCHAR(100) NOT NULL,
  `innerport_begin` VARCHAR(100) NOT NULL,
  `innerport_end` VARCHAR(100) NOT NULL,
  `comment` VARCHAR(100) NULL COMMENT '注释',
  `protocol` VARCHAR(100) NULL COMMENT '协议',
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `wk_no` VARCHAR(100) NULL COMMENT '工单号',
  `apply_person_id` INT NOT NULL COMMENT '申请人id',
  PRIMARY KEY (`id`),
  INDEX `fk_ipport_map_person1_idx` (`apply_person_id` ASC),
  CONSTRAINT `fk_ipport_map_person1`
    FOREIGN KEY (`apply_person_id`)
    REFERENCES `scmdb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `scmdb`.`case_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scmdb`.`case_info` (
  `id` VARCHAR(100) NOT NULL,
  `case_name` VARCHAR(100) NOT NULL,
  `extproduct_id` VARCHAR(100) NOT NULL COMMENT '外部产品id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `scmdb`.`case_person_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scmdb`.`case_person_map` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `relation_name` VARCHAR(100) NOT NULL COMMENT '人员角色名(\'开发\',\'测试\',\'运维\')',
  `person_id` INT NOT NULL,
  `case_info_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_case_person_map_person1_idx` (`person_id` ASC),
  INDEX `fk_case_person_map_case_info1_idx` (`case_info_id` ASC),
  CONSTRAINT `fk_case_person_map_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `scmdb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_case_person_map_case_info1`
    FOREIGN KEY (`case_info_id`)
    REFERENCES `scmdb`.`case_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `scmdb`.`person_mysql_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scmdb`.`person_mysql_map` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mysql_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_person_mysql_map_mysql1_idx` (`mysql_id` ASC),
  INDEX `fk_person_mysql_map_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_person_mysql_map_mysql1`
    FOREIGN KEY (`mysql_id`)
    REFERENCES `scmdb`.`mysql` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_mysql_map_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `scmdb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
